[phases.setup]
nixPkgs = ["nodejs_20", "python311", "ffmpeg", "pipewire", "libva"]

[phases.install]
cmds = ["pip install streamlink", "npm install --omit=dev"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmd = ["npm run start"]